version: '3.8'

services:
  frontend:
    image: node:25-alpine
    container_name: vue3-vite-app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '80:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev -- --host"
